# Generated by Django 4.2.20 on 2025-04-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_budget_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='SAMBANOVA', max_length=100)),
                ('api_key', models.CharField(max_length=255)),
            ],
        ),
    ]
